### ISSUE TITLE
No Blank Config File during Install

### ISSUE THREAD

**Issue by farrowtj** [lithnet/acma#11]
During the installation of ACMA, we had to stop during the install and create a new blank config file, otherwise the installation would fail.

- Todd F.

**Comment by ryannewington** [comment]
HI Todd,

Can you tell me a bit more about this problem?

I just tried to reproduce it with no luck. On a fresh machine, I installed ACMA, and the service started, using the default config.acmax that the installer dropped.

Thanks in advance

Ryan
