### ISSUE TITLE
Unit Test Results don't support Transforms on constants

### ISSUE THREAD

**Issue by JamieB226-westrock** [lithnet/acma#12]
When specifying unit test expected values, modifiers applied to constants don't seem to apply.  For example:

Disabled on %date%>>ToMonthDayYear by MIM

where ToMonthDayYear is a valid transform.  In this case, the output is:

Disabled on 2017-05-01T15:46:29.000>>ToMonthDayYear by MIM

This is problematic for date sensitive values because unit tests would need to be updated every time they are run (with the current date).

**Comment by JamieB226-westrock** [comment]
I initially thought this was a bug but it appears that it also doesn't work that way in other areas.  This may be a feature request instead of an actual problem with the existing code base.

**Comment by ryannewington** [comment]
Hi @JamieB226-westrock ,

Try
```
%date>>ToMonthDayYear%
```
For inline transforms, the transform chain needs to be inside the braces {attribute>>transform} for an attribute or inside the percent signs for a variable %var>>transform%. Outside of that it's considered to be plain text.

Ryan

**Comment by JamieB226-westrock** [comment]
You are correct.  That works as you described.  Thanks for the pointer.
