### ISSUE TITLE
Disabled Pre-operation events

### ISSUE THREAD

**Issue by JamieB226-westrock** [lithnet/acma#20]
Pre-operation events that are disabled seem to run anyway.  We disabled a number of events in the config file and we still see them triggered in the log file.

For example:

Event:
>      <event i:type="operation-event">
>        <description i:nil="true" />
>        <disabled>true</disabled>
>        <name>Trigger company updates</name>
>        <operation-types>full-import delta-import export</operation-types>
>        <recipient-queries>
>          <dbquery i:type="dbquery-group">
>            <description i:nil="true" />
>            <dbqueries>
>              <dbquery i:type="dbquery-group">
>                <description i:nil="true" />
>                <dbqueries>
>                  <dbquery i:type="dbquery-byvalue">
>                    <description i:nil="true" />
>                    <operator>Equals</operator>
>                    <search-attribute>
>                      <name>HRCompany</name>
>                    </search-attribute>
>                    <value-declarations>
>                      <value-declaration>
>                        <transform-string i:nil="true" />
>                        <value>WestRock Services, Inc.</value>
>                      </value-declaration>
>                    </value-declarations>
>                  </dbquery>
>                  <dbquery i:type="dbquery-byvalue">
>                    <description i:nil="true" />
>                    <operator>Equals</operator>
>                    <search-attribute>
>                      <name>HRCompany</name>
>                    </search-attribute>
>                    <value-declarations>
>                      <value-declaration>
>                        <transform-string i:nil="true" />
>                        <value>WestRock MWV  LLC</value>
>                      </value-declaration>
>                    </value-declarations>
>                  </dbquery>
>                </dbqueries>
>                <display-name i:nil="true" />
>                <operator>none</operator>
>              </dbquery>
>              <dbquery i:type="dbquery-byvalue">
>                <description i:nil="true" />
>                <operator>Equals</operator>
>                <search-attribute>
>                  <name>objectClass</name>
>                </search-attribute>
>                <value-declarations>
>                  <value-declaration>
>                    <transform-string i:nil="true" />
>                    <value>person</value>
>                  </value-declaration>
>                </value-declarations>
>              </dbquery>
>            </dbqueries>
>            <display-name i:nil="true" />
>            <operator>all</operator>
>          </dbquery>
>        </recipient-queries>
>      </event>

Log file entries:
>9/9/2017 10:36:41 AM: Sending event Trigger company updates to person:Roger Audy:0d9cdb9c-e36a-4f7c-9517-b13470a4711d
9/9/2017 10:36:41 AM:         >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
>9/9/2017 10:36:41 AM:         Processing CSEntryChange for object person:Roger Audy:0d9cdb9c-e36a-4f7c-9517-b13470a4711d 
>9/9/2017 10:36:41 AM:         Change details (this object): Modification type: Update; Changed attributes: 
>9/9/2017 10:36:41 AM:         Incoming events: Trigger company updates

**Comment by ryannewington** [comment]
Hi @JamieB226-westrock, thanks for reporting this one. Its fixed in https://github.com/lithnet/acma/releases/tag/v1.1.6462

If all is working for you, feel free to close this issue.
