### ISSUE TITLE
Editor becomes unresponsive when manipulating pre-operation events

### ISSUE THREAD

**Issue by JamieB226-westrock** [lithnet/acma#24]
I have a recurring issue with the editor when manipulating queries for pre-operation events.  It has a tendency to hang for a period of time and maybe crash.  Windows shows Not Responding and the UI is non-responsive with the timer mouse icon.  When this occurs, it may or may not let me continue working if I leave it alone.  This behavior isn't observed in other parts of the UI.  Let me know if there is any diagnostic or troubleshooting logs you need.

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/acma/releases/tag/v1.1.7238
