### ISSUE TITLE
Export operation times out on member changes for large groups (~25K)

### ISSUE THREAD

**Issue by JamieB226-westrock** [lithnet/acma#25]
When exporting the members attribute on a large group (~25K) members, the operation seems to timeout and gives the following error:

> The operation is not valid for the state of the transaction

Details:

>    at System.Transactions.TransactionState.EnlistPromotableSinglePhase(InternalTransaction tx, IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Transaction atomicTransaction, Guid promoterType)
>    at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Guid promoterType)
>    at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification)
>    at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
>    at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
>    at System.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
>    at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
>    at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
>    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
>    at System.Data.SqlClient.SqlConnection.Open()
>    at Lithnet.Acma.AcmaDatabase.GetNewConnection()
>    at Lithnet.Acma.MAObject.Commit()
>    at Lithnet.Acma.MAObjectHologram.CommitCSEntryChange(MAObjectHologram triggeringObject, IList`1 attributeChanges, IList`1 incomingEvents, IList`1 constructors, Int32 depth)
>    at Lithnet.Acma.MAObjectHologram.CommitCSEntryChange(CSEntryChange csentry, Boolean isUndeleting)
>    at Lithnet.Acma.CSEntryExport.PerformCSEntryExportUpdate(CSEntryChange csentryChange, Boolean& referenceRetryRequired)
>    at Lithnet.Acma.CSEntryExport.PutExportEntry(CSEntryChange csentry, Boolean& referenceRetryRequired)
>    at Lithnet.Acma.Service.AcmaSyncService.ExportPage(ExportRequest request)

**Comment by ryannewington** [comment]
I'm not sure if this is still an issue, but you can adjust the maximum transaction timeout for your machine through the machine.config file.

https://stackoverflow.com/questions/12055511/transaction-scope-timeout-on-10-minutes

Unfortunately it is not a setting the app can override itself.
