### ISSUE TITLE
When creating MA no interface for configuring database

### ISSUE THREAD

**Issue by sean-m** [lithnet/acma#26]
I've been going through the instructions for setting up the MA and am hitting a wall. I've configured a schema in the editor for the Lithnet.Acma database which is on another server but when attempting to add the ACMA MA on the Connectivity tab there is only a view for configuring the log path and when pressing "Next" I receive an error saying "Unable to retrieve schema. Error: 80230909" I'm running MIM 2016 with the November 2017 hotfixes installed. Any ideas?

**Comment by ryannewington** [comment]
Is there anything in the event log or acma log when this happens? Does the sync engine service account have access to the DB?

**Comment by sean-m** [comment]
Nothing about it in the acma-service.log file or Event Viewer. I added the sync service account as sysadmin on the SQL database to test and still run into the same problem.

**Comment by ryannewington** [comment]
Has the acma windows service itself started without issues?

**Comment by sean-m** [comment]
Yep, service up and running.

**Comment by sean-m** [comment]
Oh wow, just restarted the service to be sure and the MA config progressed without an issue. Thank you for taking the time to help and thank you so much for making your tools public.

**Comment by ryannewington** [comment]
Just so I have the topology right... You have the ACMA service installed on the sync server, and the ACMA database on a separate server?

**Comment by ryannewington** [comment]
Nice! you're very welcome!
