### ISSUE TITLE
FIM Sync with local service account prevents ACMA Service from Starting

### ISSUE THREAD

**Issue by jasonbellz** [lithnet/acma#29]
When the FIM Sync Service account is running with a local account (.\SyncAccount).  The ACMA Service fails to start.  The SyncServiceAuthorizationManager constructor grabs the Sync Service Account from the registry and attempts to pull the security identifier. However, it fails if the service account name is in the ".\SyncAccount" format.  

A quick fix to solve this was to change the service account to "computername\SyncAccount".

9/16/2020 11:38:54 PM: An error occurred while starting the service
****************************************
An exception has occurred in OnStart
Type: System.TypeInitializationException
Message: The type initializer for 'Lithnet.Acma.Service.SyncServiceAuthorizationManager' threw an exception.
Source: Lithnet.Acma.Service
TargetSite: Void .ctor()
StackTrace:
   at Lithnet.Acma.Service.SyncServiceAuthorizationManager..ctor()
   at Lithnet.Acma.Service.ServiceMain.StartSyncServiceHost()
   at Lithnet.Acma.Service.ServiceMain.OnStart(String[] args)
****************************************

**Comment by ryannewington** [comment]
Thanks for reporting @jasonbellz 

this has been resolved in this build -> https://github.com/lithnet/acma/releases/tag/v1.1.7568
