### ISSUE TITLE
client and sync assemblies are version incremented 

### ISSUE THREAD

**Issue by jemmiegod** [lithnet/acma#3]
Lithnet.Acma.ServiceModel.Client and Lithnet.Acma.ServiceModel.Sync do not seem to be updating the assembly version on solution builds.
This is causing the installer to see them as the same file version and not deploy new versions (1.0.0.0) during upgrades, despite the contents of the file having been changed.
This prevents the service from being started after an upgrade with the following error:

> Service cannot be started. System.TypeLoadException: Could not load type 'Lithnet.Acma.ServiceModel.IAcmaResourceService' from assembly 'Lithnet.Acma.ServiceModel.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
> at Lithnet.Acma.Service.ServiceMain.StartAcmaServiceHost()
> at Lithnet.Acma.Service.ServiceMain.OnStart(String[] args)
> at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/acma/releases/tag/v1.1.6087
