### ISSUE TITLE
Setup ended prematurely

### ISSUE THREAD

**Issue by alfgil** [lithnet/acma#30]
Installation of ACMA fails with the not-so-helpful-message: "Lithnet ACMA setup wizard ended prematuerly because of an error". Is there anybody out there? - having an idea about what caused the error or what can be done to rectify this?  Is there a logfile somewhere that can give som insight?

**Comment by ryannewington** [comment]
Hi @alfgil 

If you can run the installer from an elevated command prompt with the msiexec command line as follows, it can generate a detailed log file.

`msiexec /i Lithnet.Acma.msi /l*vx "path-to-log-file.log"`

**Comment by alfgil** [comment]
Error found! Wrong version of SQL-server! Thank you, Ryan!
