### ISSUE TITLE
Error importing ACMA Rules engine MA

### ISSUE THREAD

**Issue by tadaniel** [lithnet/acma#9]
The server encountered an unexpected error:
 
 "Could not load file or assembly 'Lithnet.Acma.ServiceModel.Sync, Version=1.1.6258.25372, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

   at Lithnet.Acma.Ecma2.ManagementAgent..ctor()

InnerException=>
none
"

**Comment by ryannewington** [comment]
ILMerge had been moved and was not merging the dependent assemblies
